// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CreateForumRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateForumRequest ) UnmarshalJSON([]byte) error { return nil }
func ( CreateForumRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateForumRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateForumRequest *CreateForumRequest

func ( CreateForumResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateForumResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CreateForumResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateForumResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateForumResponse *CreateForumResponse
