// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCa0ca59eDecodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels(in *jlexer.Lexer, out *GetThreadDetailsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "author":
			out.Author = string(in.String())
		case "forum":
			out.Forum = string(in.String())
		case "slug":
			out.Slug = string(in.String())
		case "message":
			out.Message = string(in.String())
		case "created":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Created).UnmarshalJSON(data))
			}
		case "votes":
			out.Votes = int(in.Int())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCa0ca59eEncodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels(out *jwriter.Writer, in GetThreadDetailsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	if in.Author != "" {
		const prefix string = ",\"author\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Author))
	}
	if in.Forum != "" {
		const prefix string = ",\"forum\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Forum))
	}
	if in.Slug != "" {
		const prefix string = ",\"slug\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Slug))
	}
	if in.Message != "" {
		const prefix string = ",\"message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Message))
	}
	if true {
		const prefix string = ",\"created\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Created).MarshalJSON())
	}
	if in.Votes != 0 {
		const prefix string = ",\"votes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Votes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetThreadDetailsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCa0ca59eEncodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetThreadDetailsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCa0ca59eEncodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetThreadDetailsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCa0ca59eDecodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetThreadDetailsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCa0ca59eDecodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels(l, v)
}
func easyjsonCa0ca59eDecodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels1(in *jlexer.Lexer, out *GetThreadDetailsRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "SlugOrID":
			out.SlugOrID = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCa0ca59eEncodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels1(out *jwriter.Writer, in GetThreadDetailsRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.SlugOrID != "" {
		const prefix string = ",\"SlugOrID\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.SlugOrID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetThreadDetailsRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCa0ca59eEncodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetThreadDetailsRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCa0ca59eEncodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetThreadDetailsRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCa0ca59eDecodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetThreadDetailsRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCa0ca59eDecodeLonkidelyTechnoparkDbmsForumInternalThreadDeliveryModels1(l, v)
}
